// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: package/message/branch_msg.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BranchMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*BranchMessage_Command
	//	*BranchMessage_CommandRes
	Payload isBranchMessage_Payload `protobuf_oneof:"payload"`
}

func (x *BranchMessage) Reset() {
	*x = BranchMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_package_message_branch_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BranchMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchMessage) ProtoMessage() {}

func (x *BranchMessage) ProtoReflect() protoreflect.Message {
	mi := &file_package_message_branch_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchMessage.ProtoReflect.Descriptor instead.
func (*BranchMessage) Descriptor() ([]byte, []int) {
	return file_package_message_branch_msg_proto_rawDescGZIP(), []int{0}
}

func (m *BranchMessage) GetPayload() isBranchMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *BranchMessage) GetCommand() *Command {
	if x, ok := x.GetPayload().(*BranchMessage_Command); ok {
		return x.Command
	}
	return nil
}

func (x *BranchMessage) GetCommandRes() *CommandRes {
	if x, ok := x.GetPayload().(*BranchMessage_CommandRes); ok {
		return x.CommandRes
	}
	return nil
}

type isBranchMessage_Payload interface {
	isBranchMessage_Payload()
}

type BranchMessage_Command struct {
	Command *Command `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type BranchMessage_CommandRes struct {
	CommandRes *CommandRes `protobuf:"bytes,2,opt,name=command_res,json=commandRes,proto3,oneof"`
}

func (*BranchMessage_Command) isBranchMessage_Payload() {}

func (*BranchMessage_CommandRes) isBranchMessage_Payload() {}

var File_package_message_branch_msg_proto protoreflect.FileDescriptor

var file_package_message_branch_msg_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2f, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x1a, 0x1d, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x21, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x5f, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7a, 0x0a, 0x0d, 0x42, 0x72,
	0x61, 0x6e, 0x63, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x29, 0x0a, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x33, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x5f, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x48, 0x00, 0x52,
	0x0a, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x42, 0x09, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x1d, 0x5a, 0x1b, 0x6d, 0x70, 0x33, 0x2f, 0x70, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x3b, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_package_message_branch_msg_proto_rawDescOnce sync.Once
	file_package_message_branch_msg_proto_rawDescData = file_package_message_branch_msg_proto_rawDesc
)

func file_package_message_branch_msg_proto_rawDescGZIP() []byte {
	file_package_message_branch_msg_proto_rawDescOnce.Do(func() {
		file_package_message_branch_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_package_message_branch_msg_proto_rawDescData)
	})
	return file_package_message_branch_msg_proto_rawDescData
}

var file_package_message_branch_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_package_message_branch_msg_proto_goTypes = []interface{}{
	(*BranchMessage)(nil), // 0: main.BranchMessage
	(*Command)(nil),       // 1: main.Command
	(*CommandRes)(nil),    // 2: main.CommandRes
}
var file_package_message_branch_msg_proto_depIdxs = []int32{
	1, // 0: main.BranchMessage.command:type_name -> main.Command
	2, // 1: main.BranchMessage.command_res:type_name -> main.CommandRes
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_package_message_branch_msg_proto_init() }
func file_package_message_branch_msg_proto_init() {
	if File_package_message_branch_msg_proto != nil {
		return
	}
	file_package_message_command_proto_init()
	file_package_message_command_res_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_package_message_branch_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BranchMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_package_message_branch_msg_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*BranchMessage_Command)(nil),
		(*BranchMessage_CommandRes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_package_message_branch_msg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_package_message_branch_msg_proto_goTypes,
		DependencyIndexes: file_package_message_branch_msg_proto_depIdxs,
		MessageInfos:      file_package_message_branch_msg_proto_msgTypes,
	}.Build()
	File_package_message_branch_msg_proto = out.File
	file_package_message_branch_msg_proto_rawDesc = nil
	file_package_message_branch_msg_proto_goTypes = nil
	file_package_message_branch_msg_proto_depIdxs = nil
}
