// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: package/message/command.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define the CommandType enumeration
type CommandType int32

const (
	CommandType_BEGIN    CommandType = 0
	CommandType_DEPOSIT  CommandType = 1
	CommandType_BALANCE  CommandType = 2
	CommandType_WITHDRAW CommandType = 3
	CommandType_COMMIT   CommandType = 4
	CommandType_ABORT    CommandType = 5
	CommandType_PREPARE  CommandType = 6
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "BEGIN",
		1: "DEPOSIT",
		2: "BALANCE",
		3: "WITHDRAW",
		4: "COMMIT",
		5: "ABORT",
		6: "PREPARE",
	}
	CommandType_value = map[string]int32{
		"BEGIN":    0,
		"DEPOSIT":  1,
		"BALANCE":  2,
		"WITHDRAW": 3,
		"COMMIT":   4,
		"ABORT":    5,
		"PREPARE":  6,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_package_message_command_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_package_message_command_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_package_message_command_proto_rawDescGZIP(), []int{0}
}

// Define the Command message
type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type          CommandType `protobuf:"varint,1,opt,name=Type,proto3,enum=main.CommandType" json:"Type,omitempty"`
	CoordBranchId string      `protobuf:"bytes,2,opt,name=CoordBranchId,proto3" json:"CoordBranchId,omitempty"`
	BranchId      string      `protobuf:"bytes,3,opt,name=BranchId,proto3" json:"BranchId,omitempty"`
	Account       string      `protobuf:"bytes,4,opt,name=Account,proto3" json:"Account,omitempty"`
	Amount        int32       `protobuf:"varint,5,opt,name=Amount,proto3" json:"Amount,omitempty"`
	TransacId     string      `protobuf:"bytes,6,opt,name=TransacId,proto3" json:"TransacId,omitempty"`
	Timestamp     string      `protobuf:"bytes,7,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_package_message_command_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_package_message_command_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_package_message_command_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_BEGIN
}

func (x *Command) GetCoordBranchId() string {
	if x != nil {
		return x.CoordBranchId
	}
	return ""
}

func (x *Command) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *Command) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Command) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Command) GetTransacId() string {
	if x != nil {
		return x.TransacId
	}
	return ""
}

func (x *Command) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_package_message_command_proto protoreflect.FileDescriptor

var file_package_message_command_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0xe0, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x12, 0x25, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x11, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x6f, 0x6f, 0x72,
	0x64, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2a, 0x64, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x45, 0x47, 0x49, 0x4e,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x50, 0x4f, 0x53, 0x49, 0x54, 0x10, 0x01, 0x12,
	0x0b, 0x0a, 0x07, 0x42, 0x41, 0x4c, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08,
	0x57, 0x49, 0x54, 0x48, 0x44, 0x52, 0x41, 0x57, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4f,
	0x4d, 0x4d, 0x49, 0x54, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x42, 0x4f, 0x52, 0x54, 0x10,
	0x05, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x45, 0x50, 0x41, 0x52, 0x45, 0x10, 0x06, 0x42, 0x1d,
	0x5a, 0x1b, 0x6d, 0x70, 0x33, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_package_message_command_proto_rawDescOnce sync.Once
	file_package_message_command_proto_rawDescData = file_package_message_command_proto_rawDesc
)

func file_package_message_command_proto_rawDescGZIP() []byte {
	file_package_message_command_proto_rawDescOnce.Do(func() {
		file_package_message_command_proto_rawDescData = protoimpl.X.CompressGZIP(file_package_message_command_proto_rawDescData)
	})
	return file_package_message_command_proto_rawDescData
}

var file_package_message_command_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_package_message_command_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_package_message_command_proto_goTypes = []interface{}{
	(CommandType)(0), // 0: main.CommandType
	(*Command)(nil),  // 1: main.Command
}
var file_package_message_command_proto_depIdxs = []int32{
	0, // 0: main.Command.Type:type_name -> main.CommandType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_package_message_command_proto_init() }
func file_package_message_command_proto_init() {
	if File_package_message_command_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_package_message_command_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_package_message_command_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_package_message_command_proto_goTypes,
		DependencyIndexes: file_package_message_command_proto_depIdxs,
		EnumInfos:         file_package_message_command_proto_enumTypes,
		MessageInfos:      file_package_message_command_proto_msgTypes,
	}.Build()
	File_package_message_command_proto = out.File
	file_package_message_command_proto_rawDesc = nil
	file_package_message_command_proto_goTypes = nil
	file_package_message_command_proto_depIdxs = nil
}
