// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: package/message/command_res.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandStatus int32

const (
	CommandStatus_OK        CommandStatus = 0
	CommandStatus_ABORTED   CommandStatus = 1
	CommandStatus_COMMIT_OK CommandStatus = 2
	CommandStatus_NOT_FOUND CommandStatus = 3
)

// Enum value maps for CommandStatus.
var (
	CommandStatus_name = map[int32]string{
		0: "OK",
		1: "ABORTED",
		2: "COMMIT_OK",
		3: "NOT_FOUND",
	}
	CommandStatus_value = map[string]int32{
		"OK":        0,
		"ABORTED":   1,
		"COMMIT_OK": 2,
		"NOT_FOUND": 3,
	}
)

func (x CommandStatus) Enum() *CommandStatus {
	p := new(CommandStatus)
	*p = x
	return p
}

func (x CommandStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_package_message_command_res_proto_enumTypes[0].Descriptor()
}

func (CommandStatus) Type() protoreflect.EnumType {
	return &file_package_message_command_res_proto_enumTypes[0]
}

func (x CommandStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandStatus.Descriptor instead.
func (CommandStatus) EnumDescriptor() ([]byte, []int) {
	return file_package_message_command_res_proto_rawDescGZIP(), []int{0}
}

type CommandRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransacId     string        `protobuf:"bytes,1,opt,name=TransacId,proto3" json:"TransacId,omitempty"`
	CoordBranchId string        `protobuf:"bytes,2,opt,name=CoordBranchId,proto3" json:"CoordBranchId,omitempty"`
	BranchId      string        `protobuf:"bytes,3,opt,name=BranchId,proto3" json:"BranchId,omitempty"`
	Account       string        `protobuf:"bytes,4,opt,name=Account,proto3" json:"Account,omitempty"`
	Type          CommandType   `protobuf:"varint,5,opt,name=Type,proto3,enum=main.CommandType" json:"Type,omitempty"`
	Status        CommandStatus `protobuf:"varint,6,opt,name=Status,proto3,enum=main.CommandStatus" json:"Status,omitempty"`
	Balance       int32         `protobuf:"varint,7,opt,name=Balance,proto3" json:"Balance,omitempty"`
	Timestamp     string        `protobuf:"bytes,8,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
}

func (x *CommandRes) Reset() {
	*x = CommandRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_package_message_command_res_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRes) ProtoMessage() {}

func (x *CommandRes) ProtoReflect() protoreflect.Message {
	mi := &file_package_message_command_res_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRes.ProtoReflect.Descriptor instead.
func (*CommandRes) Descriptor() ([]byte, []int) {
	return file_package_message_command_res_proto_rawDescGZIP(), []int{0}
}

func (x *CommandRes) GetTransacId() string {
	if x != nil {
		return x.TransacId
	}
	return ""
}

func (x *CommandRes) GetCoordBranchId() string {
	if x != nil {
		return x.CoordBranchId
	}
	return ""
}

func (x *CommandRes) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *CommandRes) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CommandRes) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_BEGIN
}

func (x *CommandRes) GetStatus() CommandStatus {
	if x != nil {
		return x.Status
	}
	return CommandStatus_OK
}

func (x *CommandRes) GetBalance() int32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *CommandRes) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_package_message_command_res_proto protoreflect.FileDescriptor

var file_package_message_command_res_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x1a, 0x1d, 0x70, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x92, 0x02, 0x0a, 0x0a, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x42, 0x72,
	0x61, 0x6e, 0x63, 0x68, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x43, 0x6f,
	0x6f, 0x72, 0x64, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x42,
	0x72, 0x61, 0x6e, 0x63, 0x68, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x42,
	0x72, 0x61, 0x6e, 0x63, 0x68, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x25, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x11, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2a, 0x42, 0x0a,
	0x0d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x06,
	0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x42, 0x4f, 0x52, 0x54, 0x45,
	0x44, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f, 0x4d, 0x4d, 0x49, 0x54, 0x5f, 0x4f, 0x4b,
	0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10,
	0x03, 0x42, 0x1d, 0x5a, 0x1b, 0x6d, 0x70, 0x33, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_package_message_command_res_proto_rawDescOnce sync.Once
	file_package_message_command_res_proto_rawDescData = file_package_message_command_res_proto_rawDesc
)

func file_package_message_command_res_proto_rawDescGZIP() []byte {
	file_package_message_command_res_proto_rawDescOnce.Do(func() {
		file_package_message_command_res_proto_rawDescData = protoimpl.X.CompressGZIP(file_package_message_command_res_proto_rawDescData)
	})
	return file_package_message_command_res_proto_rawDescData
}

var file_package_message_command_res_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_package_message_command_res_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_package_message_command_res_proto_goTypes = []interface{}{
	(CommandStatus)(0), // 0: main.CommandStatus
	(*CommandRes)(nil), // 1: main.CommandRes
	(CommandType)(0),   // 2: main.CommandType
}
var file_package_message_command_res_proto_depIdxs = []int32{
	2, // 0: main.CommandRes.Type:type_name -> main.CommandType
	0, // 1: main.CommandRes.Status:type_name -> main.CommandStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_package_message_command_res_proto_init() }
func file_package_message_command_res_proto_init() {
	if File_package_message_command_res_proto != nil {
		return
	}
	file_package_message_command_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_package_message_command_res_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_package_message_command_res_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_package_message_command_res_proto_goTypes,
		DependencyIndexes: file_package_message_command_res_proto_depIdxs,
		EnumInfos:         file_package_message_command_res_proto_enumTypes,
		MessageInfos:      file_package_message_command_res_proto_msgTypes,
	}.Build()
	File_package_message_command_res_proto = out.File
	file_package_message_command_res_proto_rawDesc = nil
	file_package_message_command_res_proto_goTypes = nil
	file_package_message_command_res_proto_depIdxs = nil
}
